name: Silicon Claymore
pygments: true
timezone: America/Edmonton
permalink: /forge/:year-:month-:day/:title
future: false
url: http://siliconclaymore.github.io
markdown: kramdown
gems:
  - jekyll-sitemap
